---
evaluate:
  type: "shell"
  timeout: 2500
  shell:
    entrypoint: "python"
    command:
      - "/evaluate.py"
metric:
  type: "http"
  timeout: 2500
  http:
    method: "POST"
    url: "https://metrics-server:3000/api/v1/jobs"
    successCodes:
      - 200
    headers:
      Content-Type: "application/json"
    parameterMode: body
    caCert: "/var/run/autocert.step.sm/root.crt"
    clientCert: "/var/run/autocert.step.sm/site.crt"
    clientKey: "/var/run/autocert.step.sm/site.key"
runMode: "per-resource"
