- name: "Remove Service Deployments"
  hosts: configurator
  tasks:
    - name: "Remove Sequencer Deployment"
      tags:
        - sequencer
      kubernetes.core.k8s:
        state: absent
        kind: Deployment
        namespace: "{{ cluster.namespace }}"
        name: sequencer

    - name: "Remove Sequencer Service"
      tags:
        - sequencer
      kubernetes.core.k8s:
        state: absent
        kind: Service
        namespace: "{{ cluster.namespace }}"
        name: sequencer-server
