---
- name: "Remove Service Deployments"
  hosts: localhost
  tasks:
    - name: "Remove Sequencer Deployment"
      tags:
        - sequencer
      kubernetes.core.k8s:
        state: absent
        kind: Deployment
        namespace: "{{ app.namespace }}"
        name: sequencer

    - name: "Remove Sequencer Service"
      tags:
        - sequencer
      kubernetes.core.k8s:
        state: absent
        kind: Service
        namespace: "{{ app.namespace }}"
        name: sequencer-server

    - name: Remove Sequencer AutoScaler
      tags:
        - sequencer
      kubernetes.core.k8s:
        state: absent
        namespace: "{{ app.namespace }}"
        kind: HorizontalPodAutoscaler
        name: sequencer-autoscaler

    - name: "Remove Gateway Deployment"
      tags:
        - gateway
      kubernetes.core.k8s:
        state: absent
        kind: Deployment
        namespace: "{{ app.namespace }}"
        name: gateway

    - name: "Remove Gateway Service"
      tags:
        - gateway
      kubernetes.core.k8s:
        state: absent
        kind: Service
        namespace: "{{ app.namespace }}"
        name: gateway-server

    - name: Remove Gateway AutoScaler
      tags:
        - gateway
      kubernetes.core.k8s:
        state: absent
        namespace: "{{ app.namespace }}"
        kind: HorizontalPodAutoscaler
        name: gateway-autoscaler

    - name: Remove Service Account
      tags:
        - cert-master
      kubernetes.core.k8s:
        state: absent
        name: cert-master
        kind: ServiceAccount
        namespace: "{{ app.namespace }}"

    - name: Remove ClusterRole
      tags:
        - cert-master
      kubernetes.core.k8s:
        state: absent
        name: cert-master-role
        kind: ClusterRole
        namespace: "{{ app.namespace }}"

    - name: Remove ClusterRoleBinding
      tags:
        - cert-master
      kubernetes.core.k8s:
        state: absent
        name: cert-master-role
        kind: ClusterRole
        namespace: "{{ app.namespace }}"

    - name: Remove cert-master Deployment
      tags:
        - cert-master
      kubernetes.core.k8s:
        state: absent
        name: cert-master
        kind: Deployment
        namespace: "{{ app.namespace }}"

    - name: Remove cert-master Service
      tags:
        - cert-master
      kubernetes.core.k8s:
        state: absent
        name: cert-master-server
        kind: Service
        namespace: "{{ app.namespace }}"

    - name: Remove cert-master Service
      tags:
        - cert-master
      kubernetes.core.k8s:
        state: absent
        name: cert-master-autoscaler
        kind: HorizontalPodAutoscaler
        namespace: "{{ app.namespace }}"
