---
{{- if .Values.security.cluster.tls }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "cert-master"
  labels:
    {{- include "argus.labels" . | nindent 4 }}
    app: "cert-master"
  annotations:
    {{- toYaml .Values.certmaster.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.certmaster.replicas.min }}
  selector:
    matchLabels:
      app: "cert-master"
  template:
    metadata:
      annotations:
        {{- set .Values.certmaster.podAnnotations "autocert.step.sm/name" "cert-master-server" | toYaml | nindent 8 }}
      labels:
        app: "cert-master"
    spec:
      serviceAccount: cert-master
      serviceAccountName: cert-master
      tolerations:
        {{- toYaml .Values.certmaster.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.certmaster.affinity | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.certmaster.nodeSelector | nindent 8 }}
      imagePullSecrets:
        {{- toYaml .Values.image.imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .Values.certmaster.securityContext | nindent 8 }}
      containers:
        - name: "cert-master"
          image: "{{ .Values.image.registry }}/cert-master:{{ .Values.certmaster.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "15Mi"
              cpu: "100m"
            limits:
              memory: "50Mi"
              cpu: "300m"
          env:
            # Web port
            - name: PORT
              value: "3000"

            # Redis settings
            - name: REDIS_HOST
              value: "{{ .Values.redis.fullnameOverride | default (printf "%s-redis" .Chart.Name ) }}"
            - name: REDIS_PORT
              value: "26379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.redis.fullnameOverride | default (printf "%s-redis" .Chart.Name ) }}"
                  key: redis-password

            - name: LOGLEVEL
              value: "{{ .Values.certmaster.loglevel }}"

            - name: TLS_ENABLED
              value: "TRUE"
            - name: CERT_PATH
              value: "/var/run/autocert.step.sm/site.crt"
            - name: KEY_PATH
              value: "/var/run/autocert.step.sm/site.key"
            - name: CA_PATH
              value: "/var/run/autocert.step.sm/root.crt"
{{- end }}
