---
{{- if .Values.security.cluster.tls }}
apiVersion: v1
kind: Service
metadata:
  name: "cert-master-server"
  labels:
    {{- include "argus.labels" . | nindent 4 }}
spec:
  selector:
    app: "cert-master"
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
{{- end}}
