app:
  name: howsami
  host: howsami.local

build:
  # Build all images before deploying
  enabled: true

docker:
  # Registry / account to push the images to
  #  <registry>/<image name>:<tag>
  registry: "ghcr.io/watcherwhale"

  imagePullSecrets:
    - name: ghcr-io

  # Push to registry
  push: yes

  # The tag of the build
  #  <registry>/<image name>:<tag>
  buildTag: latest

cluster:
  # The kubernetes namespace to deploy to
  namespace: howsami

redis:
  # Run all instances on speperate hosts
  hostSeperated: true

  # Docker tag of the redis pods
  tag: 6-alpine

  # Amount of redis database replicas
  # Must be at least 3
  replicas: 3

sequencer:
  # Amount of sequencer replicas
  replicas:
    min: 1
    max: 10

  # The docker tag to pull
  tag: latest

  # The docker pull poliicy
  # - Never
  # - Always
  # - IfNotPresent
  pullPolicy: Always

# All checks to deploy (and/or build) to the cluster.
#   Name is the name of the image
checks:
  - name: dns
    replicas: 1

  - name: https
    replicas: 1

  - name: ip
    replicas: 1

# Logging
fluentd:
  # Deploy fluentd
  enabled: true

  # Namespace where fluentd lives
  namespace: fluentd

  # Docker Image
  #   Best practice is to create a custom fluentd dockerfile
  #   with preinstalled plugins of choice.
  image: fluent/fluentd-kubernetes-daemonset
  tag: v1-debian-elasticsearch

  # Elasticsearch
  #   Additional settings can be configured in:
  #     ./fluentd/fluentd-config/elastic.conf
  elastic:
    enabled: false

    # Connection details
    host: elasticsearch
    port: 9200

  # Custom fluentd config file
  #   Add additional custom fluentd config options to the instance:
  #     ./fluentd/fluentd-config/custom.conf
  custom:
    enabled: false
