build:
  # Build all images before deploying
  enabled: true

docker:
  # Registry / account to push the images to
  #  <registry>/<image name>:<tag>
  registry: howsami

  # Push to registry
  push: no

  # The tag of the build
  #  <registry>/<image name>:<tag>
  buildTag: latest

cluster:
  # The kubernetes namespace to deploy to
  namespace: howsami

redis:
  # Name for the redis cluster
  # Domain: <name>-redis-sentinel.<namespace>.svc.cluster.local
  name: howsami

  # Run all instances on speperate hosts
  hostSeperated: false

  # Docker tag of the redis pods
  tag: 6-alpine

  # Amount of redis database replicas
  # Must be at least 3
  replicas: 3

sequencer:
  # Amount of sequencer replicas
  replicas: 3

  # The docker tag to pull
  tag: latest

  # The port the sequencer runs on
  port: 80

  # The docker pull poliicy
  # - Never
  # - Always
  # - IfNotPresent
  pullPolicy: IfNotPresent
