app:
  name: howsami
  host: howsami.local

build:
  # Build all images before deploying
  enabled: true

docker:
  # Registry / account to push the images to
  #  <registry>/<image name>:<tag>
  registry: "ghcr.io/watcherwhale"

  imagePullSecrets:
    - name: ghcr-io

  # Push to registry
  push: yes

  # The tag of the build
  #  <registry>/<image name>:<tag>
  buildTag: latest

  # The docker pull poliicy
  # - Never
  # - Always
  # - IfNotPresent
  pullPolicy: Always

cluster:
  # The kubernetes namespace to deploy to
  namespace: howsami

redis:
  # Run all instances on speperate hosts
  hostSeperated: true

  # Docker tag of the redis pods
  tag: 6-alpine

  # Amount of redis database replicas
  # Must be at least 3
  replicas: 3

sequencer:
  loglevel: http

  # Amount of sequencer replicas
  replicas:
    min: 1
    max: 10

  # The docker tag to pull
  tag: latest

  # The docker pull poliicy
  # - Never
  # - Always
  # - IfNotPresent
  pullPolicy: Always

# All checklists to deploy (and/or build) to the cluster.
#   Name is the name of the image
checklists:

  - name: dns

    # Amount of jobs one instance can handle
    #  in the specified interval.
    throughput: 20

    # The interval (miliseconds) to periodicaly check
    #  the size of the queue, and down/up scale
    interval: 10000

    # Amount of time (seconds) to stabilize downscaling.
    stabilization: 200

    # Define the range of amount of replicas to deploy.
    replicas:
      min: 1
      max: 5

  - name: https
    throughput: 20
    stabilization: 200
    interval: 10000
    replicas:
      min: 1
      max: 5

  - name: ip
    throughput: 20
    stabilization: 200
    interval: 10000
    replicas:
      min: 1
      max: 5

autoscaler:
  # https://github.com/jthomperoo/custom-pod-autoscaler-operator/releases
  version: v1.2.0

# Logging
fluentd:
  # Deploy fluentd
  enabled: true

  # Namespace where fluentd lives
  namespace: fluentd

  # Docker Image
  #   Best practice is to create a custom fluentd dockerfile
  #   with preinstalled plugins of choice.
  image: fluent/fluentd-kubernetes-daemonset
  tag: v1-debian-elasticsearch

  # Elasticsearch
  #   Additional settings can be configured in:
  #     ./fluentd/fluentd-config/elastic.conf
  elastic:
    enabled: false

    # Connection details
    host: elasticsearch
    port: 9200

  # Custom fluentd config file
  #   Add additional custom fluentd config options to the instance:
  #     ./fluentd/fluentd-config/custom.conf
  custom:
    enabled: false
