---
- name: "Load Config on localhost"
  hosts: localhost
  tags:
    - config
  tasks:
    - name: "Load Config on localhost"
      include_vars:
        file: ./config.yml

- import_playbook: "./build/build.yml"
  tags: build
  when: build.enabled == true

- import_playbook: "./kubernetes/setup.yml"
  tags:
    - kubernetes
    - k8s
    - setup

- import_playbook: "./autoscaler/deploy.yml"
  tags:
    - kubernetes
    - k8s
    - autoscaler

- import_playbook: "./redis/deploy.yml"
  tags:
    - kubernetes
    - k8s
    - redis

- import_playbook: "./services/gateway.yml"
  tags:
    - kubernetes
    - k8s
    - gateway

- import_playbook: "./services/sequencer.yml"
  tags:
    - kubernetes
    - k8s
    - sequencer

- import_playbook: "./checklists/deploy.yml"
  tags:
    - kubernetes
    - k8s
    - checklists

- import_playbook: "./kubernetes/ingress.yml"
  tags:
    - kubernetes
    - k8s
    - ingress

- import_playbook: "./fluentd/deploy.yml"
  tags:
    - kubernetes
    - k8s
    - fluentd
    - logging
    - log
  when: fluentd.enabled == true
