- name: Apply Fluentd Configmaps
  hosts: configurator
  tasks:
    - name: Configmap
      kubernetes.core.k8s:
        state: present
        namespace: "{{ fluentd.namespace }}"
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: fluentd-config
            namespace: "{{ fluentd.namespace }}"
          data:
            fluent.conf: |
              # Kubernetes input
              @include k8s-fluent.conf
              @include fluent-output.conf

            k8s-fluent.conf: |
              <source>
                @type tail
                read_from_head true
                tag k8s.*
                path /var/log/containers/*.log
                pos_file /var/log/fluentd-k8s.log.pos
                exclude_path ["/var/log/containers/fluent*"]
                <parse>
                  @type kubernetes
                  @type json
                  time_format %Y-%m-%dT%H:%M:%S.%NZ
                </parse>
              </source>

              <filter k8s.**>
                @type parser
                key_name log
                format json
                reserve_data true
              </filter>

              <filter k8s.**>
                @type kubernetes_metadata
                @id filter_kube_metadata
              </filter>


              # DEVELOPMENT

              <match fluent.**>
                @type null
              </match>

              <match k8s.var.log.containers.**fluentd**.log>
                @type null
              </match>

              <match **>
                @type stdout
              </match>

              # END DEVELOPMENT

            fluent-output.conf: |
              # This file is automatically generated by Ansible.

              {%if fluentd.elastic.enabled == true %}{{ lookup('file', './fluentd-config/elastic.conf') }}{%endif%}

              {%if fluentd.custom.enabled == true %}{{ lookup('file', './fluentd-config/custom.conf') }}{%endif%}
