---
- name: Setup prerequisites
  hosts: localhost
  tasks:
    - name: Create namesapce
      kubernetes.core.k8s:
        state: present
        definition:
          kind: Namespace
          apiVersion: v1
          metadata:
            name: "{{ fluentd.namespace }}"

- import_playbook: ./configmap.yml

- import_playbook: ./daemonset.yml
