- name: "Deploy Sequencer"
  hosts: configurator
  tasks:
    - name: "Deploy Containers"
      kubernetes.core.k8s:
        state: present
        namespace: "{{ cluster.namespace }}"
        definition:
          apiVersion: v1
          kind: Deployment
          metadata:
            name: "sequencer"
            labels:
              app: "sequencer"
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: "sequencer"
            template:
              metadata:
                labels:
                  app: "sequencer"
              spec:
                containers:
                  - name: "sequencer"
                    image: "{{ docker.registry }}/sequencer:{{ sequencer.tag }}"
                    imagePullPolicy: "{{ sequencer.pullPolicy }}"
                    ports:
                      - containerPort: "{{ sequencer.port }}"
                    env:
                      - name: PORT
                        value: "{{ sequencer.port | string }}"
                      - name: REDIS_HOST
                        value: "{{ redis.name }}-redis-ha-haproxy.{{ cluster.namespace }}.svc.cluster.local"

    - name: "Deploy ClusterIP Service"
      kubernetes.core.k8s:
        state: present
        namespace: "{{ cluster.namespace }}"
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: sequencer-server
          spec:
            selector:
              app: sequencer
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80
