---
- name: Deploy Ingress
  hosts: localhost
  tasks:
    - name: Load Backends
      include_vars:
        file: ./backends.yml

    - name: Deploy Ingress
      kubernetes.core.k8s:
        state: present
        namespace: "{{ app.namespace }}"
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: "{{ app.name }}-ingress"

            annotations:
              nginx.ingress.kubernetes.io/auth-tls-verify-client: "{{ (app.security.ingress.clientAuth) | ternary('on', 'off') }}"
              nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
              nginx.ingress.kubernetes.io/auth-tls-secret: "{{ (app.security.cluster.tls) | ternary( app.namespace + '/autocert-ca-certificate', (app.security.ingress.clientAuth) | ternary( app.security.ingress.caSecret, '' ) ) }}"
              nginx.ingress.kubernetes.io/secure-backends: "{{ app.security.cluster.tls | string | lower }}"
              nginx.ingress.kubernetes.io/backend-protocol: "{{ (app.security.cluster.tls) | ternary('HTTPS', 'HTTP') }}"
          spec:
            ingressClassName: nginx
            tls:
              - hosts:
                  - "{{ app.host }}"
                secretName: "{{ app.security.ingress.tlsSecret }}"
            rules:
              - host: "{{ app.host }}"
                http:
                  paths: "{{ (app.security.cluster.tls) | ternary( ingress.backends, [ ingress.backends[0] ] ) }}"
