---
- name: "Remove Kubernetes Deployments"
  hosts: localhost
  tasks:
    - name: "Remove Ingress"
      tags:
        - ingress
      kubernetes.core.k8s:
        state: absent
        kind: Ingress
        name: "{{ app.name }}-ingress"
        namespace: "{{ cluster.namespace }}"

    - name: "Remove Namespace"
      tags:
        - setup
      kubernetes.core.k8s:
        state: absent
        kind: Namespace
        name: "{{ cluster.namespace }}"
