- name: Install Required packages
  hosts: configurator
  tasks:
    - name: "Install helm"
      package:
        name: "helm"
        state: latest

- name: Setup Kubernetes
  hosts: configurator
  tasks:
    - name: "Create namespace"
      kubernetes.core.k8s:
        state: present
        definition:
          kind: Namespace
          apiVersion: v1
          metadata:
            name: "{{ cluster.namespace }}"
