---
- name: Setup Kubernetes
  hosts: localhost
  tasks:
    - name: "Create namespace"
      kubernetes.core.k8s:
        state: present
        definition:
          kind: Namespace
          apiVersion: v1
          metadata:
            name: "{{ app.namespace }}"
            labels:
              autocert.step.sm: enabled
