---
# -- App settings
app:
  # -- The name of the deployment.
  name: argus
  # -- The hostname used in the ingress.
  host: argus.local

# -- Security Settings
security:
  cluster:
    # -- Enable mTLS & TLS throughout the cluster.
    tls: false

  ingress:
    # -- Enable mTLS at the ingress.
    clientAuth: true
    # -- The Certificate Authority Certificate secret.
    caSecret: "argus-ca"
    # -- The tls secret for https.
    tlsSecret: "argus-tls"

# -- Container image settings.
image:
  # -- The image registry to use.
  registry: "ghcr.io/watcherwhale"

  # -- A list of image pull secrets to use.
  imagePullSecrets:
    - name: ghcr-io

  # -- Default pullPolicy.
  pullPolicy: IfNotPresent

# -- All services
services:
  # -- Gateway service configuration.
  # @default -- Service config
  gateway:
    # -- Log level.
    loglevel: info

    # -- Deployment annotations.
    annotations: {}
    # -- Pod annotations.
    podAnnotations: {}

    # -- Node Labels for pod assignment.
    nodeSelector: {}
    # -- Affinity for pod assignment.
    affinity: {}
    # -- Tolerations for pod assignment.
    tolerations: []

    # -- Pod security context.
    securityContext: {}

    replicas:
      # -- Minimum replicas.
      min: 1
      # -- Maximum replicas.
      max: 10

    # -- Image tag
    tag: v1.0.0

  # -- Sequencer service configuration.
  # @default -- Service config
  sequencer:
    # -- Log level.
    loglevel: info

    # -- Deployment annotations.
    annotations: {}
    # -- Pod annotations.
    podAnnotations: {}

    # -- Node Labels for pod assignment.
    nodeSelector: {}
    # -- Affinity for pod assignment.
    affinity: {}
    # -- Tolerations for pod assignment.
    tolerations: []

    # -- Pod security context.
    securityContext: {}

    replicas:
      # -- Minimum replicas.
      min: 1
      # -- Maximum replicas.
      max: 10

    # -- Image tag
    tag: v1.0.0

  # -- Descriptions service configuration.
  # @default -- Service config
  descriptions:
    # -- Deployment annotations.
    annotations: {}
    # -- Pod annotations.
    podAnnotations: {}

    # -- Node Labels for pod assignment.
    nodeSelector: {}
    # -- Affinity for pod assignment.
    affinity: {}
    # -- Tolerations for pod assignment.
    tolerations: []

    # -- Pod security context.
    securityContext: {}

    replicas:
      # -- Minimum replicas.
      min: 1
      # -- Maximum replicas.
      max: 10

    # -- Image tag
    tag: v1.0.0

  # -- Metrics service configuration.
  # @default -- Service config
  metrics:
    # -- Log level.
    loglevel: info

    # -- Deployment annotations.
    annotations: {}
    # -- Pod annotations.
    podAnnotations: {}

    # -- Node Labels for pod assignment.
    nodeSelector: {}
    # -- Affinity for pod assignment.
    affinity: {}
    # -- Tolerations for pod assignment.
    tolerations: []

    # -- Pod security context.
    securityContext: {}

    replicas:
      # -- Minimum replicas.
      min: 1
      # -- Maximum replicas.
      max: 10

    # -- Image tag
    tag: v1.0.0

  # -- Cert-master service configuration.
  # Only necessary when `security.cluster.tls` is enabled.
  # @default -- Service config
  certmaster:
    # -- Log level.
    loglevel: info

    # -- Deployment annotations.
    annotations: {}
    # -- Pod annotations.
    podAnnotations: {}

    # -- Node Labels for pod assignment.
    nodeSelector: {}
    # -- Affinity for pod assignment.
    affinity: {}
    # -- Tolerations for pod assignment.
    tolerations: []

    # -- Pod security context.
    securityContext: {}

    replicas:
      # -- Minimum replicas.
      min: 1
      # -- Maximum replicas.
      max: 10

    # -- Image tag
    tag: v1.0.0

# -- A list of all available checklists that need to be deployed.
#
# These can be customized to add your own checks.
#
# Default available checklists: `cookie`, `dns`, `headers`, `https`, `ip` and `mail`.
checklists:
  dns:
    # -- The image tag of the checklist container.
    tag: v1.0.0

    # -- Deployment annotations.
    annotations: {}
    # -- Pod annotations.
    podAnnotations: {}

    # -- Node Labels for pod assignment.
    nodeSelector: {}
    # -- Affinity for pod assignment.
    affinity: {}
    # -- Tolerations for pod assignment.
    tolerations: []

    # -- Custom environment variabled to add to the checklist.
    env: {}

    # -- Check throughput
    #
    # The amount of request the checklist can handle in an interval.
    throughput: 100
    # -- The throughput interval, the interval to periodically check the current queue size. (ms)
    interval: 10000
    # -- The stabilization interval, used for down scaling. (s)
    stabilization: 200
    replicas:
      # -- Minimum replicas
      min: 1
      # -- Maximum replicas
      max: 5

  headers:
    tag: v1.0.0

    annotations: {}
    podAnnotations: {}

    nodeSelector: {}
    affinity: {}
    tolerations: []

    env: {}

    throughput: 50
    interval: 10000
    stabilization: 200
    replicas:
      min: 1
      max: 5

  https:
    tag: v1.0.0

    annotations: {}
    podAnnotations: {}

    nodeSelector: {}
    affinity: {}
    tolerations: []

    env: {}

    throughput: 20
    interval: 10000
    stabilization: 200
    replicas:
      min: 1
      max: 5

  ip:
    tag: v1.0.0

    annotations: {}
    podAnnotations: {}

    nodeSelector: {}
    affinity: {}
    tolerations: []

    env: {}

    throughput: 1
    interval: 10000
    stabilization: 200
    replicas:
      min: 1
      max: 10

  mail:
    tag: v1.0.0

    annotations: {}
    podAnnotations: {}

    nodeSelector: {}
    affinity: {}
    tolerations: []

    env: {}

    throughput: 20
    interval: 10000
    stabilization: 200
    replicas:
      min: 1
      max: 10

  cookie:
    tag: v1.0.0

    annotations: {}
    podAnnotations: {}

    nodeSelector: {}
    affinity: {}
    tolerations: []

    env:
      SELENIUM_URL: "http://selenium-hub:4444"

    throughput: 1
    interval: 10000
    stabilization: 200
    replicas:
      min: 1
      max: 10

# -- Autoscaling configuration.
autoscaling:
  # -- Enable/Disable autoscaling.
  enabled: true

  # -- The image tag for the custom autoscaler.
  tag: v1.0.0

# -- The Selenium deployment configuration.
selenium:
  # -- Enable the Selenium deployment.
  enabled: true
  # -- The selenium hub/Chrome image tag.
  tag: latest

  # -- Amount of Chrome node replicas.
  replicas: 3

  # -- Node Labels for pod assignment.
  nodeSelector: {}
  # -- Affinity for pod assignment.
  affinity: {}
  # -- Tolerations for pod assignment.
  tolerations: []

# -- Bitnami Redis configuration.
# See https://github.com/bitnami/charts/tree/master/bitnami/redis for more config options.
# @default -- Bitnami Redis config
redis:
  # -- Master settings
  master:
    persistence:
      enabled: false

  replica:
    # Amount of replicas
    replicaCount: 3

    persistence:
      enabled: false

  sentinel:
    # -- Enable or Disable sentinels
    # Must be enabled
    enabled: true

  # -- Auth settings
  auth:
    enabled: true
    sentinel: true
