---
apiVersion: v1
kind: Service
metadata:
  name: "metrics-server"
  labels:
    {{- include "argus.labels" . | nindent 4 }}
spec:
  selector:
    app: "metrics"
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
