---
- name: "Deploy Redis Cluster"
  hosts: localhost
  tasks:
    - name: Add required helm repo
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami

    - name: Install Redis cluster
      kubernetes.core.helm:
        name: redis
        chart_ref: bitnami/redis
        namespace: "{{ cluster.namespace }}"
        values:
          master:
            persistence:
              enabled: "{{ redis.persistence }}"

          replica:
            replicaCount: "{{ redis.replicas }}"

            persistence:
              enabled: "{{ redis.persistence }}"

          sentinel:
            enabled: true

          auth:
            enabled: true
            sentinel: true
