---
- name: "Deploy Redis Cluster"
  hosts: localhost
  tasks:
    - name: Add required helm repo
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami

    - name: Install Redis cluster
      kubernetes.core.helm:
        name: redis
        chart_ref: bitnami/redis
        namespace: "{{ cluster.namespace }}"
        values:
          master:
            podAnnotations:
              autocert.step.sm/name: "redis.{{ cluster.namespace }}.svc.cluster.local"

            persistence:
              enabled: "{{ redis.persistence }}"

          replica:
            replicaCount: "{{ redis.replicas }}"

            podAnnotations:
              autocert.step.sm/name: "redis.{{ cluster.namespace }}.svc.cluster.local"

            persistence:
              enabled: "{{ redis.persistence }}"

          sentinel:
            enabled: true

          auth:
            enabled: true
            sentinel: true

          tls:
            enabled: true

            authClients: true

            autoGenerated: true
            certFilename: /var/run/autocert.step.sm/site.crt
            certKeyFilename: /var/run/autocert.step.sm/site.key
            certCAFilename: /var/run/autocert.step.sm/root.crt
