---
- name: "Remove Redis Deployments"
  hosts: localhost
  tasks:
    - name: Remove Redis cluster
      tags:
        - redis
      kubernetes.core.helm:
        name: redis
        namespace: "{{ app.namespace }}"
        state: absent
