---
name: mail
version: 0.2.0
tags:
  - mail
  - passive
  - DKIM
  - DMARC
  - SPF
type:
  - domain
stages:
  - name: "MX record"
    checks:
      - MX.py
  - name: "Mailcheck stage"
    checks:
      - DKIM.py
      - DMARC.py
      - SPF.py
