{{- if .Values.autoscaling }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: descriptions-autoscaler
  labels:
    {{- include "argus.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "descriptions"
  minReplicas: {{ .Values.descriptions.replicas.min }}
  maxReplicas: {{ .Values.descriptions.replicas.max }}
  targetCPUUtilizationPercentage: 90
{{- end}}
