---
- name: Deploy Checklist Autoscaler
  hosts: configurator
  tasks:
    - name: Install Custom Pod Autoscaler Operator
      kubernetes.core.helm:
        name: "{{ app.name }}-autoscaler-operator"
        chart_ref: "https://github.com/jthomperoo/custom-pod-autoscaler-operator/releases/download/{{ autoscaler.version }}/custom-pod-autoscaler-operator-{{ autoscaler.version }}.tgz"
        release_namespace: kube-system
