---
name: Push & Deploy
on:
  workflow_run:
    workflows:
      - Build Services
      - Build Checklists
    types:
      - completed

jobs:
  push:
    runs-on: self-hosted
    needs: test
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub container registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push checklists to GitHub
        run: ./.actions/push.sh ${GITHUB_SHA}
        working-directory: checks

      - name: Push services to GitHub
        run: ./.actions/push.sh ${GITHUB_SHA}
        working-directory: services

  deploy:
    runs-on: self-hosted
    needs: test
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: "Login to ArgoCD"
        run: argocd login ${{ secrets.ARGOCD_URL }} --insecure --username ${{ secrets.ARGOCD_USER }} --password ${{ secrets.ARGOCD_PASSWORD }}

      - name: "ArgoCD Sync"
        run: argocd app sync argus
