---
name: Push & Deploy
on:
  workflow_run:
    workflows:
      - Build Services
      - Build Checklists
    types:
      - completed

jobs:
  push:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub container registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push checklists to GitHub
        run: ./.actions/push.sh ${GITHUB_SHA}
        working-directory: checks

      - name: Push services to GitHub
        run: ./.actions/push.sh ${GITHUB_SHA}
        working-directory: services
