---
name: Push Checklists
on:
  workflow_run:
    workflows: [Build Checklists]
    branches: [master]
    types:
      - completed

jobs:
  push:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub container registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push checklists to GitHub
        run: ./.actions/push.sh ${GITHUB_SHA}
        working-directory: checks
