---
name: Python Code Style
on:
  pull_request:
    branches:
      - master

jobs:
  style:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Install Linter
        run: pip3 install pylint

      - name: Check Codestyle
        run: find . -type f -name '*.py' -exec pylint --rcfile=.pylintrc {} +
