---
name: Services
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Build service images
        run: ./.actions/build.sh
        working-directory: services

  push:
    runs-on: self-hosted
    needs: build
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Push checklists to GitHub
        run: ./.actions/push.sh
        working-directory: services
