---
name: Services
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Build service images
        run: ./.actions/build.sh ${GITHUB_SHA}
        working-directory: services

  push:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Push checklists to GitHub
        run: ./.actions/push.sh ${GITHUB_SHA}
        working-directory: services
