---
name: Services
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Build service images
        run: ./.actions/build.sh ${GITHUB_SHA}
        working-directory: services
