---
name: Yaml Code Style
on: pull_resuest

jobs:
  style:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Check Codestyle
        uses: frenck/action-yamllint@v1
