---
name: Yaml Code Style
on:
  pull_request:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check Codestyle
        uses: frenck/action-yamllint@v1
