---
name: Yaml Code Style
on:
  pull_request:
    branches:
      - master

jobs:
  style:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Lint Yaml Files
        uses: frenck/action-yamllint@v1

      - name: Lint Helm Charts
        run: helm lint --strict *
        working-directory: charts
