---
name: Yaml Code Style
on:
  pull_request:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Linter
        run: apt update && apt install -y yamllint

      - name: Check Codestyle
        run: yamllint .
